name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    environment: upload
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Mypy
        run: uv run --frozen mypy --color src/

      - name: Tests
        run: uv run --frozen pytest --color=yes -v tests

      - name: Build
        run: uv --verbose build

      - name: Publish to PyPI
        run: uv publish --verbose dist/*
        # environment 'upload', secret: UV_PUBLISH_TOKEN
